# Prelude
Hehe I really liked this activity. But I did the logistic regression a bit late and I am really out of energy now. So really sorry for doing only the required parts :c.

# Acknowledgements
I'd like to thank my instructors, Sir Rene Principe Jr. and Sir Kenneth Leo, for guiding me throughout the activity. I would also like to thank my professor, Ma'am Jing, for guiding me in my coding while my classmates and I worked in R202. I would also like to acknowledge my classmates: Abdel, Johnenn, Jonabel, Richmond, Lovely, Hans, Genesis, Jeruine, Rusher, and Ron for helping me complete this activity.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import statistics as st
from PIL import Image
from skimage.measure import label, regionprops, regionprops_table
import pandas as pd
import os
from scipy.ndimage import binary_fill_holes
from sklearn.model_selection import train_test_split

image_repository = "./Image repository/"
data_repository = "./Features extracted/"

# initializing this so I have a placeholder
image = 0
R,G,B, ave_R,ave_G, ave_B = None, None, None, None, None, None
def g(a):
    pass

In [148]:
def model(x):
    return np.sin(x)

def sigmoid(a):
    return 1/(1 + np.exp(-a))

def sigmoid_derivative(a):
    return sigmoid(a)*(1 - sigmoid(a))
    

In [145]:
def x_vectors(x, n):
    vectors = []
    for i in range(n):
        vectors.append(x**i)
    vecs = np.array(vectors)
    return np.dstack(np.split(vecs, n))


def initialize_omega(size, shape):
    weights = np.random.random(size = size)
    weights = np.reshape(weights, shape)
    return weights

In [162]:
def start_learning(data_input, omega_input1, omega_input2):
    
    # Setting up the parameters
    xi = data_input.copy()
    d = model(xi)
    omegaji = omega_input1.copy()
    omegakj = omega_input2.copy()
    aj = []
    
    # getting aj
    for i in range(len(omegaji)):
        aj.append(np.sum(np.dot(xi,omegaji[i,:])))
    
    aj = np.array(aj)
 
    # Getting gj
    gj = sigmoid(aj)
    
    # Getting ak
    ak = np.sum(np.dot(omegakj,gj))
    z = sigmoid(ak)

    # Computing the error of each output
    indiv_E = np.dot(sigmoid_derivative(np.dot(omegakj,gj)),(sigmoid(omegakj*gj) - d))
    
    # hiden error 



In [163]:
N = 4
M = 3
x_vec = x_vectors(np.arange(0, 20, 1) , N)
omega_initial_1st_layer = initialize_omega(N*M, [M,N])
omega_initial_2nd_layer = initialize_omega(M, [M,])

omega_1st_layer, omega_2nd_layer = start_learning(x_vec, omega_initial_1st_layer, omega_initial_2nd_layer)


[17788.15131238 16090.89830205 12342.79313793]


ValueError: operands could not be broadcast together with shapes (3,) (1,20,4) 

In [153]:
print(x_vec)
print(omega_initial_1st_layer)
print(omega_initial_2nd_layer)

[[[   1    0    0    0]
  [   1    1    1    1]
  [   1    2    4    8]
  [   1    3    9   27]
  [   1    4   16   64]
  [   1    5   25  125]
  [   1    6   36  216]
  [   1    7   49  343]
  [   1    8   64  512]
  [   1    9   81  729]
  [   1   10  100 1000]
  [   1   11  121 1331]
  [   1   12  144 1728]
  [   1   13  169 2197]
  [   1   14  196 2744]
  [   1   15  225 3375]
  [   1   16  256 4096]
  [   1   17  289 4913]
  [   1   18  324 5832]
  [   1   19  361 6859]]]
[[0.67609926 0.64034526 0.18621865 0.00174536]
 [0.39268382 0.90861099 0.15061905 0.67954783]
 [0.47578024 0.88675707 0.43972536 0.20660544]]
[0.3650528  0.88234878 0.05644326]


In [133]:
test = 0
for i in range(len(x_vec)):
    test += x_vec[i,:]*omega_initial_1st_layer[2,:]
print(np.sum(test))

1529.9890456086077


In [74]:
print(x_vec[3,:]*omega_initial_1st_layer[3,2])

[0.00000000e+00 1.40241306e-01 1.12193045e+00 3.78651527e+00
 8.97544360e+00 1.75301633e+01 3.02921221e+01 4.81027680e+01
 7.18035488e+01 1.02235912e+02 1.40241306e+02 1.86661179e+02
 2.42336977e+02 3.08110150e+02 3.84822144e+02 4.73314408e+02
 5.74428390e+02 6.89005537e+02 8.17887298e+02 9.61915119e+02]
